### ISSUE TITLE
postgresql view

### ISSUE THREAD

**Issue by saeed-raeisi** [teamappir/jalali_utils#2]
Hi
How to use to create a view?
`"""CREATE or REPLACE VIEW %s as (%s)""" % (self._table, self._query())`
or
`return '%s (SELECT %s FROM %s GROUP BY %s)' % (with_, select_, from_, groupby_)`
use in this query

**Comment by mehdipourfar** [comment]
Hi. Can you be more specific about your problem? Here I just see some query formatting with python and I don't understand how it relates to this package.

**Comment by saeed-raeisi** [comment]
I solved the problem
We needed to change the date and the query had to be modified

I needed to show the season that the jdatetime library did not have
add quarter #86
https://github.com/slashmili/python-jalali/pull/86
