### ISSUE TITLE
plain PLpgSQL

### ISSUE THREAD

**Issue by phpboy007** [teamappir/jalali_utils#3]
hi can i have the PLpgSQL version ?
like this one
https://github.com/mehdipourfar/pg_jalali_format

**Comment by mehdipourfar** [comment]
I didn't properly understand your question. Can explain what do you need?

**Comment by phpboy007** [comment]
I don't want it in c version
I want raw sql (.sql) file

like this repository that is now DEPRICATED
https://github.com/mehdipourfar/pg_jalali_format

**Comment by mehdipourfar** [comment]
It had some bugs with some dates which I can't remember properly. But you can copy the improved logic from jalali_utils.c and fix that code and send a merge request.
