### ISSUE TITLE
instaiotion problem

### ISSUE THREAD

**Issue by mostafakml** [teamappir/jalali_utils#4]
i try to install this extension on postgres 14 after I install 
sudo apt install postgresql-server-dev-14
run make and receive this error 
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -I. -I./ -I/usr/include/postgresql/14/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2   -c -o jalali_utils.o jalali_utils.c
make: gcc: Command not found
make: *** [<builtin>: jalali_utils.o] Error 127

**Comment by mehdipourfar** [comment]
As your error tells (`make: gcc: Command not found`), you need to install `gcc` for compilation process.
