### ISSUE TITLE
running `make install` results in a fatal error

### ISSUE THREAD

**Issue by okaeiz** [teamappir/jalali_utils#5]
Hey there! Thanks for your useful project. I had used it before its C version and it worked like a charm.
Now I cloned the repository, and I ran the following commands:
```bash
apt install postgresql-server-dev-12
apt install build-essential
```
So I ran `make install` in the root directory of the project and it keeps returning this error:
```bash
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -I. -I./ -I/usr/include/postgresql/15/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2   -c -o jalali_utils.o jalali_utils.c
jalali_utils.c:1:10: fatal error: postgres.h: No such file or directory
    1 | #include "postgres.h"
      |          ^~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: jalali_utils.o] Error 1
```
What part of the installation process am I doing wrong? I am sure postgres is installed and I can access my database via psql.

**Comment by okaeiz** [comment]
I think I got it. The `make install` command is looking for `postgres.h` in this path:
```bash
/usr/include/postgresql/15/server
```
The installation walkthrough in `README.md` suggests that we should install version 12:
```bash
apt install postgresql-server-dev-12
```
But in my case, after completely removing version 12 and installing version 15, it returned the following error:
```bash
/usr/bin/clang-11 -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -I. -I./ -I/usr/include/postgresql/15/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -flto=thin -emit-llvm -c -o jalali_utils.bc jalali_utils.c
make: /usr/bin/clang-11: No such file or directory
make: *** [/usr/lib/postgresql/15/lib/pgxs/src/makefiles/../../src/Makefile.global:1080: jalali_utils.bc] Error 127
```
which is due to `clang` not having been installed. So, I ran this:
```bash
apt update
apt install clang-11
```
Then I ran `make clean` and `make install` again. Then it was fixed. I entered `psql` and ran this:
```sql
CREATE EXTENSION jalali_utils;
```
Then I could use the SQL functions:
```sql
SELECT format_jalali(NOW());
```
Therefore, you may close this off if you confirm nothing is wrong.

**Comment by mehdipourfar** [comment]
Hey @okaeiz. Yes. It requires header files of the installed postgresql version.
